Upgrading versions and minor change to xreg.
google-research/timesfm pull request #112
Opened 2024-07-19 19:23 UTC by rajatsen91

2024-07-22 15:36 UTC, siriuz42 commented on src/timesfm/xreg_lib.py
> +        sparse_output=False,
Thanks for revising this.

2024-07-22 15:40 UTC, siriuz42 requested changes
Thanks for taking care of this. PTAL.

2024-07-22 15:40 UTC, siriuz42 commented on pyproject.toml
> +scikit-learn = ">=1.0.2"
scikit-learn = ">=1.2.2"

1.2.2 is the first version that introduced sparse_output as per the [API doc](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html).

2024-07-23 12:46 UTC, rajatsen91 commented on src/timesfm/xreg_lib.py
> +        sparse_output=False,
done.

2024-07-23 12:46 UTC, merged